### PR TITLE
Add evtest utility

### PR DESCRIPTION
**Pull request by andr2000**
This is original recipe from meta-openembedded
commit bc94e4329acce34972b42c3ed30ee28e910224ae

Signed-off-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>

### CODE REVIEW

**Review by lorc — APPROVED** [review]
`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by andr2000** [comment]
ping

**Comment by iartemenko** [comment]
lgtm

**Comment by andr2000** [comment]
pls merge

**Pull request merged**
