### PR TITLE
domx:xen: Adopt changes in XEN packages since version 4.10.0

### PR DESCRIPTION
**Pull request by aanisov**
Changes are taken from:

https://git.yoctoproject.org/cgit/cgit.cgi/meta-virtualization/commit/?id=8cf0a585e04482627c22a70585f64b183725c370
https://git.yoctoproject.org/cgit/cgit.cgi/meta-virtualization/commit/?id=c545ee541bb510b2516782ae3b8afb626c906462

Signed-off-by: Andrii Anisov <andrii_anisov@epam.com>

This is needed to switch to XEN 4.10.0 in products.

### CODE REVIEW

**Comment by otyshchenko1** [comment]
Will this change affect gen3-test1 when merged?

**Comment by aanisov** [comment]
Evolution of this layer should not affect fixed products (versions). Otherwise version fixation was not done in a proper manner.

**Comment by andr2000** [comment]
Will this change still allow building older versions of Xen?

**Comment by aanisov** [comment]
Did not check. Should we support old XEN version build?

**Comment by aanisov** [comment]
As I remember we are fixing product versions in order to keep them buildable over the time. And I really doubt we would have any reason to switch to older version of XEN in the future.

**Comment by andr2000** [comment]
Then should we move to a newer meta-virtualization instead?

**Comment by aanisov** [comment]
That is the great idea. Currently we are using different versions of meta-virtualization for dom0 and domd. But I tend to leave meta-virtualization upgrade till promoting of Renesas BSP version.

**Comment by otyshchenko1** [comment]
lgtm

**Pull request merged**
