### PR TITLE
Switch to Renesas Yocto 3.9.0

### PR DESCRIPTION
**Pull request by otyshchenko1**

### CODE REVIEW

**Comment by iartemenko** [comment]
ping

**Comment by andr2000** [comment]
I am not sure if we need this patch here: the patch changes weak assignment and I believe that the real assignment shall be defined in the corresponding product's recipe.

**Comment by lorc** [comment]
I see no problem there. If the product has no strong opinion on which kernel to use, then we decide for it.

**Comment by iartemenko** [comment]
Moving this to corresponding product's recipe.

**Pull request merged**
