### PR TITLE
doma: Fix include of xt_shared_env.inc

### PR DESCRIPTION
**Pull request by rshym**
Fixes: 10628d1 "doma: rework Android build"

### CODE REVIEW

**Comment by rshym** [comment]
Tested by successful build of domu-image-android.

**Review by varder — APPROVED** [review]
Reviewed-by: Valerii Chubar <valerii_chubar@epam.com>

**Comment by varder** [comment]
It seems that xt_shared_env.inc is made to be used for domains meta-layers. But in meta-prod-aos it is misused  in high level yocto. Hope we will fix it in the future.

**Comment by rshym** [comment]
Here I have same problem. In reworked domu-image-android, I need xt_shared_env.inc to be accessible in upper yocto. So I decided to include it in such way. Not sure that this is proper usage, but seems like it works.

**Comment by rshym** [comment]
Reviewer was added.
Please merge.

**Pull request merged**
