### PR TITLE
doma: Switch VIS by XT_USE_VIS_SERVER

### PR DESCRIPTION
**Pull request by rshym**
This PR is 3rd implementation of #212 "doma: Switch VIS components".
PR is re-created because original PR contains "RB.." and "Tested.." that became not relevant after few proposition to rework code.
To avoid misleading info, I re-created PR to start new review and testing.

### CODE REVIEW

**Review by varder — COMMENTED** [review]
Can we have this changes in separate domu-image-android.bbappend?

**Comment by rshym** [comment]
> Can we have this changes in separate domu-image-android.bbappend?

We can, but this will be no good solution, because this is not prod-devel specific change, but will be needed for other products that use android as well.

**Comment by lorc** [comment]
`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by arminn** [comment]
Reviewed-by: Andrii Chepurnyi <andrii_chepurnyi@epam.com>

**Comment by rshym** [comment]
Reviewers are added.
Please merge.

**Pull request merged**
