### PR TITLE
URIs: replace git protoco with https one for the github sources.

### PR DESCRIPTION
**Pull request by iusyk**
URIs: replace git protocol at https one for the github sources.
Use https instead of git because unauthenticated git protocol is disabled by github.

### CODE REVIEW

**Comment by rshym** [comment]
It could be better to squash both commits.

Also good to reword the commit message to something like
"Use `https` instead of `git` because unauthenticated `git` protocol is disabled by github."

**Comment by iusyk** [comment]
> It could be better to squash both commits.
> 
> Also good to reword the commit message to something like "Use `https` instead of `git` because unauthenticated `git` protocol is disabled by github."

you are right

**Comment by lorc** [comment]
Also, would you please rephrase description header? Such split headers are hard to read with git log --oneline

And, I'm not sure that "Fix: " is a good prefix. Maybe something like "URIs: "?

**Comment by rshym** [comment]
Small comment regarding message only.
As far as I know, it's incorrect to say "replace A at B".
We should use "replace A with B".

With this small fix in message:
`Reviewed-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>`

**Pull request merged**
