### PR TITLE
Introduce xen-4.14-thud.inc

### PR DESCRIPTION
**Pull request by otyshchenko1**
What's new:
- added everything related to xenhypfs: packages, files, etc
- added dependency to python for xenmon
- updated LIC_FILES_CHKSUM
- extended FILES_${PN}-misc_append with vchan-socket-proxy

Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>

### CODE REVIEW

**Comment by otyshchenko1** [comment]
There should be corresponding PR to meta-xt-prod-devel to include this file which I am going to push later on.

**Comment by otyshchenko1** [comment]
Corresponding PR at https://github.com/xen-troops/meta-xt-prod-devel/pull/275

**Comment by andr2000** [comment]
I'm just curious why each time we introduce next version we have a lot of packages defined ourselves? Does it mean that upstream recipe still has no good Xen support? I see some essential libraries we are adding which I would expect be already present in the base recipe.

**Comment by otyshchenko1** [comment]
> I'm just curious why each time we introduce next version we have a lot of packages defined ourselves? Does it mean that upstream recipe still has no good Xen support? I see some essential libraries we are adding which I would expect be already present in the base recipe.

One part of the newly added file contains libxenhypfs/xenhypfs bits (this is completely new tool which hasn't reached base recipe yet). But, the presence of other packages (which are already in the base recipe) worth reconsidering, agree.

**Comment by otyshchenko1** [comment]
> > I'm just curious why each time we introduce next version we have a lot of packages defined ourselves? Does it mean that upstream recipe still has no good Xen support? I see some essential libraries we are adding which I would expect be already present in the base recipe.
> 
> One part of the newly added file contains libxenhypfs/xenhypfs bits (this is completely new tool which hasn't reached base recipe yet). But, the presence of other packages (which are already in the base recipe) worth reconsidering, agree.

BTW, this file could be trimmed heavily, with the following being present in do_install_append():
`rm -rf ${D}/usr/lib/pkgconfig || true`
`rm -rf ${D}/usr/lib/xenfsimage || true`
`rm -rf ${D}/usr/lib/libxenfsimage.* || true`

**Comment by otyshchenko1** [comment]
As agreed, we need to investigate what is missing in the basic recipe/what needs to be changed in it. In addition, I believe that https://github.com/xen-troops/meta-xt-images/blob/master/recipes-domx/meta-xt-images-domx/recipes-extended/xen/xen-common.inc could be trimmed as well.

**Comment by otyshchenko1** [comment]
We decided to merge it as is for now.

**Pull request merged**
