### PR TITLE
cleaning graphic recipes

### PR DESCRIPTION
**Pull request by iusyk**
according to renesas-rcar/meta-renesas@cf3bea7

### CODE REVIEW

**Comment by otyshchenko1** [comment]
Do we need to keep that files https://github.com/xen-troops/meta-xt-prod-devel/blob/master/recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/mesa/mesa_%25.bbappend / https://github.com/xen-troops/meta-xt-prod-devel/blob/master/recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-graphics/mesa/mesa_%25.bbappend then?

**Comment by otyshchenko1** [comment]
Looks like https://github.com/xen-troops/meta-xt-images/pull/146 already contains this patch. If so, this PR could be closed.

**Comment by iusyk** [comment]
> Do we need to keep that files https://github.com/xen-troops/meta-xt-prod-devel/blob/master/recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/mesa/mesa_%25.bbappend / https://github.com/xen-troops/meta-xt-prod-devel/blob/master/recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-graphics/mesa/mesa_%25.bbappend then?

I think you are right, i'll remove it from domd and domu

**Comment by iusyk** [comment]
> Looks like #146 already contains this patch. If so, this PR could be closed.

i;ll recheck and close if it is not necessary

**Comment by iusyk** [comment]
see pr 154, the changes from 145 and 146 are placed in 154

**Pull request closed without merging**
