### PR TITLE
u-boot: Remove outdated u-boot_2015.04.bbappend

### PR DESCRIPTION
**Pull request by rshym**
File has no corresponding recipe and produces warning
"No recipes available for"

### CODE REVIEW

**Review by iusyk — APPROVED** [review]
Reviewed-by: Ihor Usyk <ihor_usyk@epam.com>

**Comment by rshym** [comment]
Patch is tested by build of domd - corresponding warning is not reported.

**Comment by rshym** [comment]
Reviewer is added.

**Comment by rshym** [comment]
Patch is already implemented in 73417b2287cce926a2ff0b4dd464b8c0ba07ffdf and merged into master.

**Pull request closed without merging**
