### PR TITLE
Rel v6.0

### PR DESCRIPTION
**Pull request by iusyk**
Add the ability to customize the branch and revisions for
meta-selinux
meta-virtualization
meta-clang

Also, remove t=rcar-gen3-xen from BBFILE_COLLECTIONS because of the duplication

### CODE REVIEW

**Comment by rshym** [comment]
As I see in sources of git fetcher, parameter "name" is used to specify one or more branches that need to be fetched. But as I understand, there are no such branches in mentioned projects. I mean there is no branch `meta-selinux` in project `meta-selinux`.
And same for other projects.

**Comment by rshym** [comment]
Forgot one issue - incorrect signature in second commit.
```
Signed-off-by: xen-troops-buildbot <not.real.email@epam.com>
```

**Comment by iusyk** [comment]
> Forgot one issue - incorrect signature in second commit.
> 
> ```
> Signed-off-by: xen-troops-buildbot <not.real.email@epam.com>
> ```

agree

**Comment by iusyk** [comment]
> As I see in sources of git fetcher, parameter "name" is used to specify one or more branches that need to be fetched. But as I understand, there are no such branches in mentioned projects. I mean there is no branch `meta-selinux` in project `meta-selinux`.
> And same for other projects.

**Pull request closed without merging**
