### PR TITLE
Provide LAYERSERIES_COMPAT_ to layers

### PR DESCRIPTION
**Pull request by rshym**
Add
LAYERSERIES_COMPAT_meta-xt-images-* = "thud"
to layers.

Signed-off-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>

### CODE REVIEW

**Comment by rshym** [comment]
Fixed meta-xt-images-rcar-gen3-xen.

**Comment by rshym** [comment]
Tested by build of
- devel-u/domD
- devel-u/dom0

**Comment by rshym** [comment]
I have added citation from Yocto Mega-Manual with explanation of reason of patch, in order to address comment for similar patch in prod-devel.

**Review by iusyk — APPROVED** [review]

**Comment by andr2000** [comment]
`Acked-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>`

**Pull request merged**
