### PR TITLE
OP-TEE: Fix master branch (3.9) build

### PR DESCRIPTION
**Pull request by lorc**

### CODE REVIEW

**Comment by iusyk** [comment]
My opinion, commit 'python3: provide pyelftools recipe'  does not bring any result, because there is a host-python and, this instance of python does not have any clue what has been installed inside the yocto environment, 
The test of this recipe at the 'clear' environment brought the error 
|   INSTALL out/arm-plat-rcar/export-ta_arm64/lib/libutils.a
|   INSTALL out/arm-plat-rcar/export-ta_arm64/lib/libmbedtls.a
|
| ***
| Can't find elftools module. Probably it is not installed on your system.
| You can install this module with
|
| $ apt install python3-pyelftools
|
| if you are using Ubuntu. Or try to search for "pyelftools" or "elftools" in
| your package manager if you are using some other distribution.

It means, that python can not find the packages installed in yocto

**Comment by lorc** [comment]
That was another issue cause by patch to OP-TEE itself. That patch cause all scripts to use only \usr\bin\python3 no matter of what. Now this is fixed.

**Comment by iusyk** [comment]
Looks good to me

**Comment by arminn** [comment]
Reviewed-by: Andrii Chepurnyi andrii_chepurnyi@epam.com

**Comment by lorc** [comment]
Tags updated

**Pull request merged**
